version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: covid_postgres
    environment:
      POSTGRES_USER: covid_user
      POSTGRES_PASSWORD: covid_pass
      POSTGRES_DB: covid_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: