# version: '3.8'

# x-airflow-common: &airflow-common
#   image: apache/airflow:2.9.3
#   user: "${AIRFLOW_UID:-50000}:0"
#   environment:
#     AIRFLOW__CORE__EXECUTOR: LocalExecutor
#     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow_user:airflow_pass@airflow_postgres/airflow_db
#     AIRFLOW__CORE__FERNET_KEY: ''
#     AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
#     AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
#   volumes:
#     - ./dags:/opt/airflow/dags
#     - ./logs:/opt/airflow/logs
#     - ./plugins:/opt/airflow/plugins
#     - ./scripts:/opt/airflow/scripts   
#   depends_on:
#     airflow_postgres:
#       condition: service_healthy

# services:
#   postgres:
#     image: postgres:15
#     container_name: covid_postgres
#     environment:
#       POSTGRES_USER: covid_user
#       POSTGRES_PASSWORD: covid_pass
#       POSTGRES_DB: covid_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   airflow_postgres:
#     image: postgres:15
#     container_name: airflow_postgres
#     environment:
#       POSTGRES_USER: airflow_user
#       POSTGRES_PASSWORD: airflow_pass
#       POSTGRES_DB: airflow_db
#     ports:
#       - "5433:5432"
#     volumes:
#       - airflow_postgres_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD", "pg_isready", "-U", "airflow_user", "-d", "airflow_db"]
#       interval: 5s
#       retries: 5

#   airflow-init:
#     <<: *airflow-common
#     container_name: airflow_init
#     entrypoint: /bin/bash
#     command:
#       - -c
#       - |
#         airflow db migrate &&
#         airflow users create \
#           --username admin \
#           --firstname Admin \
#           --lastname User \
#           --role Admin \
#           --email admin@example.com \
#           --password admin

#   airflow-webserver:
#     <<: *airflow-common
#     container_name: airflow_webserver
#     command: webserver
#     ports:
#       - "8080:8080"
#     healthcheck:
#       test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
#       interval: 10s
#       timeout: 10s
#       retries: 5
#     restart: always

#   airflow-scheduler:
#     <<: *airflow-common
#     container_name: airflow_scheduler
#     command: scheduler
#     restart: always

# volumes:
#   postgres_data:
#   airflow_postgres_data:

version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:3.2.2
  user: "${AIRFLOW_UID:-50000}:0"
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow_user:airflow_pass@airflow_postgres/airflow_db
    AIRFLOW__CORE__FERNET_KEY: '4so5xhcdvwNyUibzXq2I7c2Md-nxFYlrs7L430x6384='  
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./scripts:/opt/airflow/scripts
  depends_on:
    airflow_postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    container_name: covid_postgres
    environment:
      POSTGRES_USER: covid_user
      POSTGRES_PASSWORD: covid_pass
      POSTGRES_DB: covid_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow_postgres:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow_user
      POSTGRES_PASSWORD: airflow_pass
      POSTGRES_DB: airflow_db
    ports:
      - "5433:5432"
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow_user", "-d", "airflow_db"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
    restart: on-failure       

  airflow-apiserver:
    <<: *airflow-common
    container_name: airflow_apiserver
    command: api-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/monitor/health"]  
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    restart: always
    depends_on:
      airflow_postgres:
        condition: service_healthy
      airflow-apiserver:
        condition: service_healthy   

volumes:
  postgres_data:
  airflow_postgres_data: